version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh #bu veri tabanı sunucusu ayaga kaldırılmadan önce bu scripti çalışır
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres